# Generated by Django 4.0.4 on 2022-04-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotionfmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('rname', models.CharField(max_length=100)),
                ('account_no', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=100)),
                ('acctype', models.CharField(max_length=100)),
                ('ifsc', models.CharField(max_length=100)),
                ('biz_name', models.CharField(max_length=100)),
                ('biz_type', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('weburl', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'promotionform1',
            },
        ),
    ]
